# Generated by Django 4.1.5 on 2023-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_rename_first_name_admission_registration_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_registration',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
