# Generated by Django 4.1.5 on 2023-02-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_rename_category_slide_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slide_images',
            new_name='slide_image',
        ),
    ]
