# Generated by Django 4.1.5 on 2023-02-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_rename_choreographer_team_choreography_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choreography_team',
            old_name='C_id',
            new_name='ch_id',
        ),
    ]
