# Generated by Django 4.1.5 on 2023-03-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0031_alter_dance_session_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_Batch_Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.TextField(max_length=100, null=True)),
                ('Category', models.CharField(choices=[('dance', 'Dance'), ('zumba', 'Zumba'), ('music', 'Music')], max_length=100)),
                ('Sub_Category', models.CharField(blank=True, default='Guitar', max_length=50, null=True)),
                ('Level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('Offline_payment', models.BooleanField(default=False)),
                ('Online_Payment', models.BooleanField(default=False)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dance_session',
            name='Level',
            field=models.CharField(choices=[('basic', 'basic'), ('intermadiate', 'Intermediate'), ('Advance', 'Advance')], max_length=100),
        ),
        migrations.DeleteModel(
            name='purchase',
        ),
    ]
