# Generated by Django 4.1.5 on 2023-03-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_alter_choreography_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='choreography_team',
            name='image',
            field=models.ImageField(upload_to='contents/'),
        ),
    ]
