# Generated by Django 4.1.7 on 2023-03-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0048_remove_selebrity_workshop_image_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(choices=[('Celebrity_workshop', 'Celebrity_workshop'), ('Garba_workshop_&_event', 'Garba_workshop_&_event'), ('Yearly_festival', 'Yearly_festival'), ('Achievement', 'Achievement')], max_length=100)),
                ('name_title', models.TextField(max_length=100)),
                ('image_upload', models.ImageField(upload_to='contents/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Selebrity_workshop_image',
        ),
    ]
