# Generated by Django 4.1.7 on 2023-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0052_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='Attendence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='duration',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.TextField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Low', 'Low'), ('you are terminated', 'you are terminated')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
