# Generated by Django 4.1.7 on 2023-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0057_remove_add_scorestudenttable_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_scorestudenttable',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_scorestudenttable',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
