# Generated by Django 4.1 on 2023-01-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contents_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contents',
            new_name='Category',
        ),
    ]
