# Generated by Django 4.1.5 on 2023-01-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
