# Generated by Django 4.1.5 on 2023-01-05 09:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
