# Generated by Django 4.1.5 on 2023-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_admission_registration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dance_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Level', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
