# Generated by Django 4.1.5 on 2023-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_paid',
            field=models.IntegerField(default=False),
        ),
    ]
