# Generated by Django 4.1.5 on 2023-02-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_purchase_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='slide_images',
        ),
    ]
