# Generated by Django 4.1.5 on 2023-02-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_rename_slide_images_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('choose_level', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
