# Generated by Django 4.1.5 on 2023-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_choreographer_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choreographer_Team',
            new_name='Choreography_Team',
        ),
    ]
