# Generated by Django 4.1.5 on 2023-03-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_item_remove_purchase_product_purchase_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='instamojo_response',
            new_name='Amount',
        ),
    ]
