# Generated by Django 4.1.5 on 2023-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_rename_instamojo_response_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance_session',
            name='Level',
            field=models.CharField(choices=[('basic', 'Basic'), ('Intermidate', 'intermidate'), ('advance', 'Advance')], max_length=50),
        ),
    ]
