# Generated by Django 4.1.5 on 2023-03-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_rename_regular_batch_payments_regular_batch_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular_batch_payment',
            name='Amount',
        ),
        migrations.AddField(
            model_name='regular_batch_payment',
            name='Remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regular_batch_payment',
            name='paid_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
