# Generated by Django 4.1.5 on 2023-03-05 12:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_rename_order_form_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
