# Generated by Django 4.1.5 on 2023-03-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_multipleimage_alter_choreography_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.ImageField(upload_to='contents/'),
        ),
    ]
