# Generated by Django 4.1.7 on 2023-03-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0044_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_category', models.CharField(choices=[('event', 'event'), ('workshop', 'workshop'), ('class', 'class')], max_length=50)),
                ('name_title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('image_upload', models.ImageField(upload_to='contents/')),
                ('event_Category', models.ImageField(choices=[('selebrity', 'selebrity'), ('Garba', 'Garba'), ('Achivement', 'Achivement'), ('Yealy_festival', 'Year_festival')], max_length=50, upload_to='')),
            ],
        ),
    ]
