# Generated by Django 4.1.7 on 2023-03-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0046_alter_gallery_event_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='Selebrity_workshop_image',
        ),
    ]
