# Generated by Django 4.1.7 on 2023-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0047_rename_gallery_selebrity_workshop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selebrity_workshop_image',
            name='event_Category',
        ),
        migrations.AlterField(
            model_name='selebrity_workshop_image',
            name='image_category',
            field=models.CharField(choices=[('event', 'event'), ('workshop', 'workshop'), ('class', 'class')], max_length=100),
        ),
    ]
