# Generated by Django 4.1.7 on 2023-03-25 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0054_score_total_days_score_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='month',
            field=models.CharField(default='January', max_length=20),
        ),
        migrations.CreateModel(
            name='add_ScoreStudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='January', max_length=20)),
                ('status', models.TextField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Low', 'Low'), ('you are terminated', 'you are terminated')], max_length=50)),
                ('Attendence', models.IntegerField(blank=True, null=True)),
                ('Total_days', models.IntegerField(default='31')),
                ('DanceMarks', models.IntegerField(default='/20')),
                ('score', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('EndDate', models.DateField(null=True)),
                ('StartDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.admission_registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
