# Generated by Django 4.1.7 on 2023-03-25 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0056_rename_user_add_scorestudenttable_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_scorestudenttable',
            name='users',
        ),
        migrations.AddField(
            model_name='add_scorestudenttable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
